spring:
  application:
    name: spring-6-auth-server

server:
  port: 9000

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true